apiVersion: batch/v1
kind: Job
metadata:
  name: docker
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: docker
        image: natpdev/docker-pull
        volumeMounts:
          - mountPath: /var/run/docker.sock:ro
            name: docker-sock
      restartPolicy: Never
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock