apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose.yaml -o ./k8s/test/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: eth
  name: eth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eth
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose.yaml -o ./k8s/test/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        app: eth
        # product: dapp-workers
    spec:
      containers:
        - env:
            - name: ETH_ADDR
              value: http://0.0.0.0:8545
            - name: SEED
              value: cruel rebel frown short month love belt weather sense hood cage pact
          image: natpdev/eth
          name: eth
          ports:
            - containerPort: 8545
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose.yaml -o ./k8s/test/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: eth
    # product: dapp-workers
  name: eth
spec:
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
  selector:
    app: eth
  type: LoadBalancer
