apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs0
  name: ipfs0
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ipfs0
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: ipfs0
    spec:
      containers:
        - image: ipfs/go-ipfs:latest
          name: ipfs0
          ports:
            - containerPort: 4001
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-data
      restartPolicy: Always
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
            claimName: ipfs-data
status: {}
