apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: monte-carlo-dice
  name: monte-carlo-dice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: monte-carlo-dice
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: monte-carlo-dice
    spec:
      containers:
        - env:
            - name: IPFS_HOST
          image: monte-carlo-dice
          name: monte-carlo-dice
          resources: {}
      restartPolicy: Always
status: {}
