apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: wasienv-compiler
  name: wasienv-compiler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wasienv-compiler
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose_private.yaml -o ./k8s/test_private/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: wasienv-compiler
    spec:
      containers:
        - env:
            - name: IPFS_HOST
          image: wasienv-compiler
          name: wasienv-compiler
          resources: {}
      restartPolicy: Always
status: {}
