version: "3"
services:
  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:latest
    ports:
      - "4001:4001" 
      - "8080:8080"
    volumes:
      - ipfs-data:/data/ipfs
  ethprod:
    image: ethereum/client-go:latest
    profiles:
      - prod
    ports:
      - "8545:8545"
      - "8546"
      - "8547"
      - "30303"
    labels:
      kompose.service.type: LoadBalancer
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s      
    volumes:
      - keys:/keys
  runner:
    image: runner
    profiles:
      - images
    build: images/runner
  rust-compiler:
    image: rust-compiler
    profiles:
      - images
    build: images/compiler/rust
    labels:
      kompose.service.type: LoadBalancer
  wasienv-compiler:
    profiles:
      - images    
    build: images/compiler/wasienv
    image: wasienv-compiler
  wasi-service:
    profiles:
      - images    
    build: images/wasi-service
    image: wasi-service  
  eth:
    image: eth
    build: eth
    ports:
      - "8545:8545"
    environment:
      - SEED=cruel rebel frown short month love belt weather sense hood cage pact
      - ETH_ADDR=http://0.0.0.0:8545
    profiles:
      - debug    
  nexus:
    image: nexus
    build: nexus
    environment:
      - SEED=cruel rebel frown short month love belt weather sense hood cage pact
      - ETH_ADDR=ws://eth:8545
    command: ["/bin/bash", "/app/nexus/wait-for-it.sh", "--timeout=5", "eth:8545", "--", "npx", "hardhat", "test", "--network", "tests"]
    profiles:
      - debug   
    depends_on:
      - "eth"
    links:
      - eth
  orchestrator:
    image: orchestrator
    build: services/orchestrator
    environment:
      - SEED=cruel rebel frown short month love belt weather sense hood cage pact
      - ETH_ADDR=ws://eth:8545
      - COMPOSE_PROFILES
      - NODE_OPTIONS=--openssl-legacy-provider
      - ADDRESS=0x1af5e6689288F69BBAE9E41fC6BE1C82d008935f
    command: ["/bin/bash", "/app/orchestrator/wait-for-it.sh", "--timeout=5", "eth:8545", "--", "node", "./dist/index.js"]
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./nexus:/nexus
    depends_on:
      - "eth"
      - "nexus"
    links:
      - eth
  dspportal:
    image: dspportal
    build: uis/jobs
    ports:
      - 8888:80
    depends_on:
      - "eth"
    links:
      - eth
  faucet:
    image: faucet
    build: services/faucet
    ports:
      - 8010:8080
    environment:
      - SEED=cruel rebel frown short month love belt weather sense hood cage pact
      - PORT=8080
      - ETH_ADDR=ws://eth:8545
      - NODE_OPTIONS=--openssl-legacy-provider
    profiles:
      - faucet
    depends_on:
      - "eth"
    links:
      - eth
  db:
    image: postgres
    profiles:
      - donotstart    
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
       - pg-data:/var/lib/postgresql/data/pgdata
  rabbitmq:
    profiles:
      - donotstart    
    image: rabbitmq
    ports:
      - 5672:5672
      - 8080:15672
    volumes:
      - rabbit-data:/var/lib/rabbitmq
volumes:
  keys:
    external: false
  pg-data:
    external: false
  rabbit-data:
    external: false    
  ipfs-data:
    external: false       
  nexus:
    external: false    
