apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ipfs0
  name: ipfs0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs0
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ipfs0
        product: dapp-workers
    spec:
      containers:
        - image: ipfs/go-ipfs:latest
          name: ipfs0
          ports:
            - containerPort: 4001
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /data/ipfs
              name: ipfs-data
      restartPolicy: Always
      volumes:
        - name: ipfs-data
          persistentVolumeClaim:
            claimName: ipfs-data
status: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ipfs0
    product: dapp-workers
  name: ipfs0
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: ipfs0
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: ipfs-data
  name: ipfs-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
