apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose_kms.yaml -o ./k8s/test_kms/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: nexus
  name: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nexus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose_kms.yaml -o ./k8s/test_kms/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: nexus
    spec:
      containers:
        - args:
            - /bin/bash
            - /app/nexus/wait-for-it.sh
            - --timeout=15
            - eth:8545
            - --
            - npx
            - hardhat
            - --network
            - tests
            - test
            - test/KMS.spec.js
          env:
            - name: ADDRESS
              value: 0x9d8e2c06e418e6c61785a7e4c65dd447ddc25aa0
            - name: ETH_ADDR
              value: ws://eth:8545
            - name: PRIVATE_KEY
              value: 0x278c2ff8b0fa8bbe04c430a66c828f8b2386a0e9c075b8923d257c3be30c697d
            - name: SEED
              value: cruel rebel frown short month love belt weather sense hood cage pact
            - name: WORKER_AWS_KMS_ACCESS_KEY_ID
            - name: WORKER_AWS_KMS_ENABLED
            - name: WORKER_AWS_KMS_KEY_ID
            - name: WORKER_AWS_KMS_REGION
            - name: WORKER_AWS_KMS_SECRET_ACCESS_KEY
          image: nexus
          name: nexus
          resources: {}
          volumeMounts:
            - mountPath: /services/orchestrator
              name: nexus-claim0
      restartPolicy: Always
      volumes:
        - name: nexus-claim0
          persistentVolumeClaim:
            claimName: nexus-claim0
status: {}
