apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose_kms.yaml -o ./k8s/test_kms/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orchestrator
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose_kms.yaml -o ./k8s/test_kms/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      containers:
        - args:
            - /bin/bash
            - /app/orchestrator/wait-for-it.sh
            - --timeout=15
            - eth:8545
            - --
            - node
            - ./dist/index.js
          env:
            - name: ADDRESS
              value: 0xFB5708c88C17DD7506DB21f8ecA92221Ab87d7dB
            - name: DATABASE_NODE_ENV
              value: '"production"'
            - name: DATABASE_TIMEOUT
              value: "10000"
            - name: DATABASE_URL
              value: postgres://user:password@postgres:5432/orchestrator
            - name: ETH_ADDR
              value: ws://eth:8545
            - name: FROM_BLOCK
              value: "0"
            - name: NODE_OPTIONS
              value: --openssl-legacy-provider
            - name: SEED
              value: cruel rebel frown short month love belt weather sense hood cage pact
            - name: WORKER_AWS_KMS_ACCESS_KEY_ID
            - name: WORKER_AWS_KMS_ADDRESS
              value: 0x9d8e2c06e418e6c61785a7e4c65dd447ddc25aa0
            - name: WORKER_AWS_KMS_ENABLED
            - name: WORKER_AWS_KMS_KEY_ID
            - name: WORKER_AWS_KMS_REGION
            - name: WORKER_AWS_KMS_SECRET_ACCESS_KEY
            - name: WORKER_EVM_GAS_LIMIT
              value: "1000000"
            - name: WORKER_EVM_GAS_PRICE
              value: "2000000000"
            - name: WORKER_EVM_MAX_FEE_PER_GAS
              value: "100000000000"
            - name: WORKER_EVM_MAX_PRIORITY_FEE_PER_GAS
              value: "3000000000"
          image: orchestrator
          name: orchestrator
          resources: {}
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: orchestrator-claim0
              readOnly: true
            - mountPath: /nexus
              name: orchestrator-claim1
      restartPolicy: Always
      volumes:
        - name: orchestrator-claim0
          persistentVolumeClaim:
            claimName: orchestrator-claim0
            readOnly: true
        - name: orchestrator-claim1
          persistentVolumeClaim:
            claimName: orchestrator-claim1
status: {}
