apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f local_compose.yaml
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: git-cloner
  name: git-cloner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: git-cloner
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f local_compose.yaml
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: git-cloner
    spec:
      containers:
        - env:
            - name: IPFS_HOST
          image: git-cloner
          name: git-cloner
          resources: {}
      restartPolicy: Always
status: {}
