apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f local_compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  ports:
    - name: "8050"
      port: 8050
      targetPort: 8050
  selector:
    io.kompose.service: orchestrator
status:
  loadBalancer: {}
