apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f local_compose.yaml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: runner
  name: runner
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: runner
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f local_compose.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: runner
    spec:
      containers:
        - image: runner
          name: runner
          resources: {}
      restartPolicy: Always
status: {}
