export const approvedImages = [{
    name:'wasi-service',
    type:'service'
},{
    name:'poa-evm',
    type:'service'
},{
    name:'runner',
    type:'job'
},{
    name:'nvidia-docker',
    type:'job'
},{
    name:'git-cloner',
    type:'job'
},{
    name:'sol-runner',
    type:'job'
},{
    name:'monte-carlo',
    type:'job'
},{
    name:'rust-compiler',
    type:'job'
}]