export const approvedImages = [{
    name:'natpdev/wasi-service',
    type:'service'
},{
    name:'natpdev/poa-evm',
    type:'service'
},{
    name:'natpdev/runner',
    type:'job'
},{
    name:'natpdev/nvidia-docker',
    type:'job'
},{
    name:'natpdev/git-cloner',
    type:'job'
},{
    name:'natpdev/sol-runner',
    type:'job'
},{
    name:'natpdev/monte-carlo',
    type:'job'
},{
    name:'natpdev/rust-compiler',
    type:'job'
}]