apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f test_compose.yaml -o ./k8s/test/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    app: $WORKERS_SERVICE_NAME
    product: dapp-workers-images
    image: git-cloner
  name: $WORKERS_SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $WORKERS_SERVICE_NAME
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f test_compose.yaml -o ./k8s/test/
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        app: $WORKERS_SERVICE_NAME
        product: dapp-workers-images
        image: git-cloner
    spec:
      containers:
        - env:
            - name: IPFS_HOST
          image: natpdev/git-cloner
          name: $WORKERS_SERVICE_NAME
          resources: {}
      restartPolicy: Always
status: {}
