apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
    product: dapp-workers
  name: api
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8050
  selector:
    app: api
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: api
  serviceName: "api"
  replicas: 2
  template:
    metadata:
      labels:
        app: api
        product: dapp-workers
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - args:
          - node
          - ./dist/index.js
        env:
            - name: ADDRESS
              value: $ADDRESS
            - name: ETH_ADDR
              value: $ETH_ADDR
            - name: IPFS_HOST
              value: $IPFS_HOST
        image: natpdev/api
        name: api
        ports:
        - containerPort: 8050
          name: web
