apiVersion: v1
kind: Service
metadata:
  labels:
    app: $WORKERS_SERVICE_NAME
    product: dapp-workers-images
    image: wasi-service
  name: $WORKERS_SERVICE_NAME
spec:
  ports:
    - name: $WORKERS_SERVICE_NAME
      port: 80
      targetPort: 9000
  selector:
    app: $WORKERS_SERVICE_NAME
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: $WORKERS_SERVICE_NAME
  annotations:
    kubernetes.io/ingress-bandwidth: 10M
    kubernetes.io/egress-bandwidth: 10M
spec:
  selector:
    matchLabels:
      app: $WORKERS_SERVICE_NAME
  serviceName: $WORKERS_SERVICE_NAME
  replicas: 1
  template:
    metadata:
      labels:
        app: $WORKERS_SERVICE_NAME
        product: dapp-workers-images
        image: wasi-service
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: natpdev/wasi-service
        name: $WORKERS_SERVICE_NAME
        ports:
          - containerPort: 9000
            name: $WORKERS_SERVICE_NAME
        env:
          - name: IPFS_HOST
            value: $IPFS_HOST
          - name: ARG_0
            value: $ARG_0
          - name: ARG_1
            value: $ARG_1