apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
  name: prometheus
  namespace: helm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prometheus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus
    spec:
      containers:
      - image: natpdev/prometheus_setup:v1
        name: prometheus-setup-9swhz
        resources: {}
status: {}
