apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
  name: prometheus
  namespace: helm
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  type: NodePort
status:
  loadBalancer: {}
