apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: grafana
    app.kubernetes.io/managed-by: Helm
  name: grafana
  namespace: helm
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
  type: NodePort
status:
  loadBalancer: {}
