apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dspportal
  name: dspportal
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dspportal
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dspportal
    spec:
      containers:
        - image: dspportal
          name: dspportal
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
