apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: eth
  name: eth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
        kompose.service.type: LoadBalancer
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: eth
    spec:
      containers:
        - command:
            - geth
            - --syncmode=light
            - --ws
            - --http
            - --http.addr=0.0.0.0
            - --ws.addr=0.0.0.0
          image: ethereum/client-go:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8545
            failureThreshold: 3
            periodSeconds: 90
            timeoutSeconds: 10
          name: eth
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 8547
            - containerPort: 30303
          resources: {}
          volumeMounts:
            - mountPath: /keys
              name: keys
      restartPolicy: Always
      volumes:
        - name: keys
          persistentVolumeClaim:
            claimName: keys
status: {}
