apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
    kompose.service.type: LoadBalancer
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: eth-tcp
  name: eth-tcp
spec:
  ports:
    - name: "8545"
      port: 8545
      targetPort: 8545
    - name: "8546"
      port: 8546
      targetPort: 8546
    - name: "8547"
      port: 8547
      targetPort: 8547
    - name: "30303"
      port: 30303
      targetPort: 30303
  selector:
    io.kompose.service: eth
  type: LoadBalancer
status:
  loadBalancer: {}
