apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f production_compose.yaml -o ./k8s/production/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: ipfs0
  name: ipfs0
spec:
  ports:
    - name: "4001"
      port: 4001
      targetPort: 4001
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: ipfs0
status:
  loadBalancer: {}
